# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIdwuRhRu7FwCByoDGQ7h6saxVTu3R_Q
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

def generate_supermarket_data(n_rows=1500):
    # Фиксируем seed для воспроизводимости
    np.random.seed(42)
    random.seed(42)

    branches = ['A', 'B', 'C']
    product_lines = ['Health and beauty', 'Electronic accessories',
                     'Home and lifestyle', 'Sports and travel', 'Food and beverages']

    start_date = datetime(2023, 1, 1)

    data = {
        'Invoice ID': [f"INV-{np.random.randint(10000, 99999)}" for _ in range(n_rows)],
        'User_ID': np.random.randint(100, 500, n_rows), # Симуляция повторных покупок
        'Date': [(start_date + timedelta(days=random.randint(0, 90))).strftime('%Y-%m-%d') for _ in range(n_rows)],
        'Branch': np.random.choice(branches, n_rows),
        'Product line': np.random.choice(product_lines, n_rows),
        'Unit price': np.random.uniform(10.0, 100.0, n_rows).round(2),
        'Quantity': np.random.randint(1, 10, n_rows),
        'Rating': np.random.uniform(2.0, 10.0, n_rows).round(1)
    }

    df = pd.DataFrame(data)
    df['Total'] = df['Unit price'] * df['Quantity']

    df.loc[np.random.choice(df.index, 50, replace=False), 'Rating'] = np.nan
    df['Total'] = df['Total'].apply(lambda x: f"{x:,.2f}")

    df.to_csv('supermarket_sales_mock.csv', index=False)
    print("датасет сгенерирован")

if __name__ == "__main__":
    generate_supermarket_data()